# Deliverable 3. Create a Travel Itinerary Map.
----
1. Import the vacation CSV file. 
2. From the map above with pick 4 cities that are in close proximity (on the same continent) that the customer would travel to and create a directions layer map.
3. For the "travel_mode" use either "DRIVING", "BICYCLING", or "WALKING".
4. Take a screenshot of the route and save it. 
5. Then create a marker layer for the four cities. Each city will should have a pop-up marker that contains
    - The hotel name
    - The city
    - The country
    - The current weather description and the maximum temperature
---

## Make sure the initial dependencies and the Google API key are imported.

In [20]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

In [21]:
# Configure gmaps
gmaps.configure(api_key=g_key)

## From your `Vacation_Search` folder from Deliverable 2, import the `WeatherPy_vacation.csv` file as a DataFrame named `vacation_df`

In [36]:
# Read the WeatherPy_vacation.csv into a DataFrame
vacation_df = pd.read_csv("../vacation_search/WeatherPy_vacation.csv")


# Display sample data
vacation_df.head(30)

,City_ID,City_ID.1,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,2,Aksu,CN,82.42,clear sky,41.12,80.26,Pudong Holiday Hotel
1,1,7,Touros,BR,80.60,broken clouds,-5.20,-35.46,INN NEW HORIZON
2,2,10,Morehead,US,75.20,clear sky,37.27,-87.18,CCI Express Inn
3,3,11,Port Elizabeth,ZA,84.20,clear sky,-33.92,25.57,39 On Nile Guest House
4,4,16,Northam,GB,82.40,few clouds,51.03,-4.22,Durrant House Hotel
5,5,18,Hyderabad,IN,87.01,haze,17.38,78.47,"Taj Krishna, Hyderabad"
6,6,20,Port Alfred,ZA,82.00,clear sky,-33.59,26.89,The Halyards Hotel
7,7,22,Atuona,PF,79.72,clear sky,-9.80,-139.03,Villa Enata
8,8,23,Kapaa,US,73.40,heavy intensity rain,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
9,9,25,Nikolskoye,RU,88.00,clear sky,59.70,30.79,Tourist House - Sablino
10,10,28,Arraial Do Cabo,BR,78.80,clear sky,-22.97,-42.03,Pousada Porto Praia
11,11,29,Luganville,VU,77.72,light rain,-15.53,167.17,The Espiritu Hotel
12,12,31,Dwarka,IN,87.39,clear sky,22.24,68.97,Hotel Narayan Avezika Comfort
13,13,37,Guanare,VE,82.24,light rain,9.04,-69.74,Nuevo Hotel Coromoto
14,14,38,Butaritari,KI,82.87,few clouds,3.07,172.79,Isles Sunset Lodge
15,15,41,Mata,PT,84.27,broken clouds,40.68,-7.46,Solar dos Pedrosos
16,16,42,Oussouye,SN,77.00,overcast clouds,12.48,-16.55,Auberge du Routard
17,17,44,Vaini,TO,71.60,scattered clouds,-21.20,-175.20,Keleti Beach Resort
18,18,47,Rikitea,PF,72.30,clear sky,-23.12,-134.97,Pension Maro'i
19,19,50,Suwalki,PL,77.09,light rain,54.11,22.93,Hotel Szyszko
20,20,54,Sfantu Gheorghe,RO,77.00,light rain,45.87,25.78,Hotel Park Sfantu Gheorghe
21,21,56,Pringsewu,ID,74.59,light rain,-5.36,104.97,Urban Style by Front One
22,22,57,Nacala,MZ,82.40,scattered clouds,-14.54,40.67,Nacala Plaza Business Design Hotel
23,23,61,Puerto Ayora,EC,72.00,scattered clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
24,24,63,Korla,CN,83.08,overcast clouds,41.76,86.15,Gulisitan Hotel
25,25,64,Hithadhoo,MV,84.67,broken clouds,-0.60,73.08,Scoop Guest House
26,26,66,Souillac,MU,73.40,scattered clouds,-20.52,57.52,Bils' Villa
27,27,72,Bredasdorp,ZA,73.40,clear sky,-34.53,20.04,Bredasdorp Country Manor
28,28,73,Grand Gaube,MU,73.00,clear sky,-20.01,57.66,Veranda Paul et Virginie Hotel & Spa
29,29,75,Bonthe,SL,82.78,light rain,7.53,-12.51,Bonthe Holiday Village

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [23]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## In this step, you will set-up the pop-up markers. Review the code to create a marker layer map of the vacation search results. This code is the same as in Deliverable 2.

In [24]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [31]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

## From the vacation search map, *choose four cities* that a customer might want to visit. They should be close together and in the same country.

In [37]:
# Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df["City"] == "Morehead"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Morehead"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Lufkin"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Touros"]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Vaini"]

## Use the `to_numpy()` function and list indexing to write code to retrieve the latitude-longitude pairs as tuples from each city DataFrame.

In [38]:
# Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

## Use the [gmaps documentation](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#directions-layer) to create a directions layer map using the variables from the previous step. Where the starting and ending city are the same city, the `waypoints` are the three other cities, and the `travel_mode` is either `"DRIVING"`, `"BICYCLING"`, or `"WALKING"`.

In [39]:
# Define a new figure object
fig = gmaps.figure()

# Create a direction layer map using the start and end latitude-longitude pairs, and stop1, stop2, and stop3 as the waypoints.
# The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
vacation_itinerary = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')

# Add the layer to the map
fig.add_layer(vacation_itinerary)

# Display the map
fig

Figure(layout=FigureLayout(height='420px'))

## Use the provided `concat()` function code snippet to combine the four separate city DataFrames into one DataFrame.

In [40]:
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat(
    [
        vacation_start,
        vacation_stop1,
        vacation_stop2,
        vacation_stop3
    ],
    ignore_index = True
)

# Display sample data
itinerary_df

,City_ID,City_ID.1,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,10,Morehead,US,75.2,clear sky,37.27,-87.18,CCI Express Inn
1,39,96,Lufkin,US,75.2,broken clouds,31.34,-94.73,Courtyard by Marriott Lufkin
2,1,7,Touros,BR,80.6,broken clouds,-5.20,-35.46,INN NEW HORIZON
3,17,44,Vaini,TO,71.6,scattered clouds,-21.20,-175.20,Keleti Beach Resort

## Refactor the code from Step 6 to create a new marker layer map of the cities on the travel route.

In [42]:
# Review the formatting template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Get the data from each row and add it to the formatting template and store the data in a list
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [43]:
# Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Define a new figure object
fig = gmaps.figure()

# Add the layer to the map
fig.add_layer(marker_layer)

# Display the map
fig

Figure(layout=FigureLayout(height='420px'))